language: node_js

cache: npm

node_js:
  - stable

install:
  - npm ci

script:
  - npm run test-lib
  - npm run build-lib

# do not use after_script as it executed after deploy, that you deploy or not.
before_deploy:
  - npm run ci-process-cover && cd dist/ngx-matomo

deploy:
  provider: npm
  email: $NPM_PUBLIC_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
